import enum, uuid
from datetime import datetime
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, JSON, String, Text, UniqueConstraint, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base

def uid(): return str(uuid.uuid4())
class RoleName(str, enum.Enum): visitor="visitor"; curator="curator"; admin="admin"
class ReviewStatus(str, enum.Enum): draft="draft"; pending_review="pending_review"; changes_requested="changes_requested"; approved="approved"; rejected="rejected"; published="published"; archived="archived"
class TimestampMixin:
    created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
class User(Base,TimestampMixin):
    __tablename__="users"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); full_name:Mapped[str]=mapped_column(String(255)); preferred_language:Mapped[str]=mapped_column(String(5),default="ar"); is_active:Mapped[bool]=mapped_column(Boolean,default=True); is_deleted:Mapped[bool]=mapped_column(Boolean,default=False); roles=relationship("Role",secondary="user_roles",back_populates="users")
class Role(Base):
    __tablename__="roles"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(40),unique=True); users=relationship("User",secondary="user_roles",back_populates="roles")
class UserRole(Base):
    __tablename__="user_roles"; user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),primary_key=True); role_id:Mapped[int]=mapped_column(ForeignKey("roles.id"),primary_key=True)
class Museum(Base,TimestampMixin):
    __tablename__="museums"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name_ar:Mapped[str]=mapped_column(String(255)); name_en:Mapped[str]=mapped_column(String(255)); city:Mapped[str]=mapped_column(String(120)); description_ar:Mapped[str]=mapped_column(Text,default=""); description_en:Mapped[str]=mapped_column(Text,default="")
class Collection(Base,TimestampMixin):
    __tablename__="collections"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); museum_id:Mapped[str]=mapped_column(ForeignKey("museums.id")); name_ar:Mapped[str]=mapped_column(String(255)); name_en:Mapped[str]=mapped_column(String(255)); museum=relationship("Museum")
class ArtifactCategory(Base):
    __tablename__="artifact_categories"; id:Mapped[int]=mapped_column(primary_key=True); slug:Mapped[str]=mapped_column(String(80),unique=True); name_ar:Mapped[str]=mapped_column(String(120)); name_en:Mapped[str]=mapped_column(String(120)); enabled:Mapped[bool]=mapped_column(Boolean,default=True)
class Artifact(Base,TimestampMixin):
    __tablename__="artifacts"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); slug:Mapped[str]=mapped_column(String(120),unique=True,index=True); collection_id:Mapped[str|None]=mapped_column(ForeignKey("collections.id"),nullable=True); category_id:Mapped[int|None]=mapped_column(ForeignKey("artifact_categories.id"),nullable=True); title_ar:Mapped[str]=mapped_column(String(255)); title_en:Mapped[str]=mapped_column(String(255)); description_ar:Mapped[str]=mapped_column(Text); description_en:Mapped[str]=mapped_column(Text); historical_period_ar:Mapped[str]=mapped_column(String(255),default="غير محدد"); historical_period_en:Mapped[str]=mapped_column(String(255),default="Unspecified"); estimated_date_ar:Mapped[str]=mapped_column(String(255),default="غير مؤكد"); estimated_date_en:Mapped[str]=mapped_column(String(255),default="Uncertain"); origin_ar:Mapped[str]=mapped_column(String(255),default="غير مؤكد"); origin_en:Mapped[str]=mapped_column(String(255),default="Uncertain"); material_ar:Mapped[str]=mapped_column(String(255),default="غير مؤكد"); material_en:Mapped[str]=mapped_column(String(255),default="Uncertain"); confidence:Mapped[float]=mapped_column(Float,default=1.0); verification_status:Mapped[str]=mapped_column(String(50),default="verified_demo"); review_status:Mapped[str]=mapped_column(String(50),default="published"); is_demo:Mapped[bool]=mapped_column(Boolean,default=False); is_published:Mapped[bool]=mapped_column(Boolean,default=False); image_url:Mapped[str]=mapped_column(String(500),default="/demo/pottery.svg"); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); category=relationship("ArtifactCategory"); stories=relationship("ArtifactStory",cascade="all,delete-orphan"); timeline_events=relationship("TimelineEvent",cascade="all,delete-orphan"); facts=relationship("ArtifactFact",cascade="all,delete-orphan"); hotspots=relationship("ArtifactHotspot",cascade="all,delete-orphan"); quizzes=relationship("Quiz",cascade="all,delete-orphan")
class ArtifactImage(Base,TimestampMixin):
    __tablename__="artifact_images"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str|None]=mapped_column(ForeignKey("artifacts.id"),nullable=True); path:Mapped[str]=mapped_column(String(500)); mime_type:Mapped[str]=mapped_column(String(80)); size_bytes:Mapped[int]=mapped_column(Integer); width:Mapped[int]=mapped_column(Integer); height:Mapped[int]=mapped_column(Integer)
class ArtifactAnalysis(Base,TimestampMixin):
    __tablename__="artifact_analyses"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); user_id:Mapped[str|None]=mapped_column(ForeignKey("users.id"),nullable=True); image_id:Mapped[str]=mapped_column(ForeignKey("artifact_images.id")); artifact_id:Mapped[str|None]=mapped_column(ForeignKey("artifacts.id"),nullable=True); status:Mapped[str]=mapped_column(String(80),default="queued"); current_stage:Mapped[str]=mapped_column(String(80),default="queued"); progress:Mapped[int]=mapped_column(Integer,default=0); started_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); completed_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); error_message:Mapped[str|None]=mapped_column(Text,nullable=True); retry_count:Mapped[int]=mapped_column(Integer,default=0); result_json:Mapped[dict]=mapped_column(JSON,default=dict)
class ArtifactIdentificationCandidate(Base,TimestampMixin):
    __tablename__="artifact_identification_candidates"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); analysis_id:Mapped[str]=mapped_column(ForeignKey("artifact_analyses.id")); possible_name:Mapped[str]=mapped_column(String(255)); confidence:Mapped[float]=mapped_column(Float); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)
class AIGeneration(Base,TimestampMixin):
    __tablename__="ai_generations"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str|None]=mapped_column(ForeignKey("artifacts.id"),nullable=True); generation_type:Mapped[str]=mapped_column(String(80)); provider:Mapped[str]=mapped_column(String(80)); model_name:Mapped[str]=mapped_column(String(120)); prompt_version:Mapped[str]=mapped_column(String(40)); confidence:Mapped[float|None]=mapped_column(Float,nullable=True); input_tokens:Mapped[int|None]=mapped_column(Integer,nullable=True); output_tokens:Mapped[int|None]=mapped_column(Integer,nullable=True); output_json:Mapped[dict]=mapped_column(JSON,default=dict)
class ArtifactStory(Base,TimestampMixin):
    __tablename__="artifact_stories"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); language:Mapped[str]=mapped_column(String(5)); audience:Mapped[str]=mapped_column(String(30)); title:Mapped[str]=mapped_column(String(255)); content:Mapped[str]=mapped_column(Text); verified:Mapped[bool]=mapped_column(Boolean,default=False)
class ArtifactTimeline(Base,TimestampMixin):
    __tablename__="artifact_timelines"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); language:Mapped[str]=mapped_column(String(5)); title:Mapped[str]=mapped_column(String(255))
class TimelineEvent(Base,TimestampMixin):
    __tablename__="timeline_events"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); year_label_ar:Mapped[str]=mapped_column(String(120)); year_label_en:Mapped[str]=mapped_column(String(120)); title_ar:Mapped[str]=mapped_column(String(255)); title_en:Mapped[str]=mapped_column(String(255)); description_ar:Mapped[str]=mapped_column(Text); description_en:Mapped[str]=mapped_column(Text); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class ArtifactFact(Base,TimestampMixin):
    __tablename__="artifact_facts"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); text_ar:Mapped[str]=mapped_column(Text); text_en:Mapped[str]=mapped_column(Text); verified:Mapped[bool]=mapped_column(Boolean,default=True)
class ArtifactHotspot(Base,TimestampMixin):
    __tablename__="artifact_hotspots"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); x:Mapped[float]=mapped_column(Float); y:Mapped[float]=mapped_column(Float); label_ar:Mapped[str]=mapped_column(String(255)); label_en:Mapped[str]=mapped_column(String(255)); description_ar:Mapped[str]=mapped_column(Text); description_en:Mapped[str]=mapped_column(Text); image_url:Mapped[str|None]=mapped_column(String(500),nullable=True); audio_url:Mapped[str|None]=mapped_column(String(500),nullable=True)
class Quiz(Base,TimestampMixin):
    __tablename__="quizzes"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); language:Mapped[str]=mapped_column(String(5)); title:Mapped[str]=mapped_column(String(255)); questions=relationship("QuizQuestion",cascade="all,delete-orphan")
class QuizQuestion(Base,TimestampMixin):
    __tablename__="quiz_questions"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); quiz_id:Mapped[str]=mapped_column(ForeignKey("quizzes.id")); question:Mapped[str]=mapped_column(Text); choices:Mapped[list]=mapped_column(JSON); correct_index:Mapped[int]=mapped_column(Integer); explanation:Mapped[str]=mapped_column(Text); difficulty:Mapped[str]=mapped_column(String(30),default="easy")
class QuizAttempt(Base,TimestampMixin):
    __tablename__="quiz_attempts"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); quiz_id:Mapped[str]=mapped_column(ForeignKey("quizzes.id")); user_id:Mapped[str|None]=mapped_column(ForeignKey("users.id"),nullable=True); score:Mapped[int]=mapped_column(Integer); total:Mapped[int]=mapped_column(Integer); answers:Mapped[list]=mapped_column(JSON)
class KnowledgeSource(Base,TimestampMixin):
    __tablename__="knowledge_sources"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); title:Mapped[str]=mapped_column(String(255)); organization:Mapped[str]=mapped_column(String(255)); url:Mapped[str|None]=mapped_column(String(500),nullable=True); publication_date:Mapped[str|None]=mapped_column(String(40),nullable=True); language:Mapped[str]=mapped_column(String(5)); trust_level:Mapped[str]=mapped_column(String(30),default="curator_verified"); verification_status:Mapped[str]=mapped_column(String(30),default="verified"); usage_notes:Mapped[str]=mapped_column(Text,default="Original demo content")
class KnowledgeDocument(Base,TimestampMixin):
    __tablename__="knowledge_documents"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); source_id:Mapped[str]=mapped_column(ForeignKey("knowledge_sources.id")); filename:Mapped[str]=mapped_column(String(255)); path:Mapped[str]=mapped_column(String(500)); mime_type:Mapped[str]=mapped_column(String(100)); processing_status:Mapped[str]=mapped_column(String(40),default="pending"); error_message:Mapped[str|None]=mapped_column(Text,nullable=True)
class DocumentChunk(Base,TimestampMixin):
    __tablename__="document_chunks"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); document_id:Mapped[str]=mapped_column(ForeignKey("knowledge_documents.id")); content:Mapped[str]=mapped_column(Text); chunk_index:Mapped[int]=mapped_column(Integer); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); embedding_json:Mapped[list]=mapped_column(JSON,default=list)
class Embedding(Base,TimestampMixin):
    __tablename__="embeddings"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); chunk_id:Mapped[str]=mapped_column(ForeignKey("document_chunks.id"),unique=True); model_name:Mapped[str]=mapped_column(String(120)); dimensions:Mapped[int]=mapped_column(Integer); vector_json:Mapped[list]=mapped_column(JSON)
class ArtifactSourceReference(Base,TimestampMixin):
    __tablename__="artifact_source_references"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); source_id:Mapped[str]=mapped_column(ForeignKey("knowledge_sources.id")); citation_label:Mapped[str]=mapped_column(String(255)); relevance:Mapped[float]=mapped_column(Float,default=1.0)
class Conversation(Base,TimestampMixin):
    __tablename__="conversations"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); user_id:Mapped[str|None]=mapped_column(ForeignKey("users.id"),nullable=True); language:Mapped[str]=mapped_column(String(5)); messages=relationship("Message",cascade="all,delete-orphan")
class Message(Base,TimestampMixin):
    __tablename__="messages"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); conversation_id:Mapped[str]=mapped_column(ForeignKey("conversations.id")); role:Mapped[str]=mapped_column(String(20)); content:Mapped[str]=mapped_column(Text); citations:Mapped[list]=mapped_column(JSON,default=list)
class SavedExperience(Base,TimestampMixin):
    __tablename__="saved_experiences"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); user_id:Mapped[str]=mapped_column(ForeignKey("users.id")); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); __table_args__=(UniqueConstraint("user_id","artifact_id"),)
class Narration(Base,TimestampMixin):
    __tablename__="narrations"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); language:Mapped[str]=mapped_column(String(5)); provider:Mapped[str]=mapped_column(String(80)); audio_url:Mapped[str|None]=mapped_column(String(500),nullable=True); text:Mapped[str]=mapped_column(Text)
class CuratorReview(Base,TimestampMixin):
    __tablename__="curator_reviews"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); curator_id:Mapped[str]=mapped_column(ForeignKey("users.id")); status:Mapped[str]=mapped_column(String(40)); section_statuses:Mapped[dict]=mapped_column(JSON,default=dict); notes:Mapped[str]=mapped_column(Text,default="")
class PublicationRecord(Base,TimestampMixin):
    __tablename__="publication_records"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); artifact_id:Mapped[str]=mapped_column(ForeignKey("artifacts.id")); published_by:Mapped[str]=mapped_column(ForeignKey("users.id")); version:Mapped[int]=mapped_column(Integer,default=1); snapshot:Mapped[dict]=mapped_column(JSON,default=dict)
class AuditLog(Base):
    __tablename__="audit_logs"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); actor_id:Mapped[str|None]=mapped_column(ForeignKey("users.id"),nullable=True); action:Mapped[str]=mapped_column(String(120),index=True); entity_type:Mapped[str]=mapped_column(String(80)); entity_id:Mapped[str|None]=mapped_column(String(36),nullable=True); details:Mapped[dict]=mapped_column(JSON,default=dict); ip_address:Mapped[str|None]=mapped_column(String(80),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,index=True)
class SystemSetting(Base,TimestampMixin):
    __tablename__="system_settings"; key:Mapped[str]=mapped_column(String(120),primary_key=True); value:Mapped[dict]=mapped_column(JSON); is_public:Mapped[bool]=mapped_column(Boolean,default=False)
Index("ix_artifact_publish",Artifact.is_published,Artifact.review_status)
