from app.db.session import SessionLocal,engine
from app.db.base import Base
from app.models import *
from app.core.security import hash_password
from app.core.config import settings
Base.metadata.create_all(engine)
DATA=[
{"slug":"najdi-coffee-pot","title_ar":"دلة نجدية تقليدية","title_en":"Traditional Najdi Coffee Pot","cat":"metalwork","image":"/demo/dallah.svg","period_ar":"القرنان التاسع عشر والعشرون","period_en":"19th–20th centuries","date_ar":"تأريخ تقريبي؛ غير منسوب لصانع محدد","date_en":"Approximate dating; no specific maker attributed","origin_ar":"وسط الجزيرة العربية، على الأرجح","origin_en":"Central Arabia, likely","material_ar":"نحاس أو سبيكة نحاسية، بحسب السمات الظاهرة","material_en":"Copper or copper alloy, based on visible characteristics","desc_ar":"دلة ذات هيئة مرتبطة بتقاليد إعداد وتقديم القهوة العربية. المحتوى تجريبي مكتوب خصيصًا للمنصة، ولا يمثل تعرّفًا آليًا على صورة مرفوعة.","desc_en":"A dallah form associated with preparing and serving Arabic coffee. This is original demo content and does not represent AI recognition of an uploaded image.","story_ar":"في مجلسٍ نجدي، لم تكن الدلة مجرد إناء. كانت بداية حوار، وإشارة إلى الترحيب، وجزءًا من ترتيب اجتماعي يتعلم فيه الصغير من الكبير آداب التقديم. هذه القصة تفسير تعليمي مبني على سياق ثقافي عام، وليست سيرة موثقة لهذه القطعة بعينها.","story_en":"In a Najdi gathering, the dallah was more than a vessel. It opened a conversation, signaled welcome, and formed part of a social practice in which younger generations learned serving etiquette. This is an educational interpretation based on general cultural context, not a documented biography of this specific object.","facts_ar":["ترتبط القهوة العربية بالضيافة في مجتمعات الجزيرة العربية.","تختلف أشكال الدلال وزخارفها باختلاف المناطق والفترات.","لا يمكن تحديد الصانع أو السنة الدقيقة من الشكل وحده."],"facts_en":["Arabic coffee is associated with hospitality across Arabian communities.","Dallah forms and decoration vary by region and period.","A maker or exact year cannot be established from shape alone."],"timeline":[("قبل القرن 19","Before the 19th c.","تقاليد الضيافة","Hospitality traditions","تطورت ممارسات إعداد القهوة وتقديمها ضمن الحياة الاجتماعية.","Coffee preparation and serving practices developed within social life."),("القرن 19","19th century","انتشار أشكال معدنية مميزة","Distinct metal forms","ازدادت صناعة وتداول أواني القهوة المعدنية في المنطقة.","Metal coffee vessels became increasingly produced and circulated in the region."),("الوقت الحاضر","Present day","رمز ثقافي حي","A living cultural symbol","ما زالت الدلة حاضرة في الضيافة والتصميم والهوية البصرية.","The dallah remains present in hospitality, design, and visual identity.")]},
{"slug":"hejaz-door-panel","title_ar":"لوح باب حجازي مزخرف","title_en":"Decorated Hejazi Door Panel","cat":"architecture","image":"/demo/door.svg","period_ar":"أواخر العهد العثماني إلى بدايات القرن العشرين، تقديريًا","period_en":"Late Ottoman to early 20th century, estimated","date_ar":"غير مؤكدة","date_en":"Uncertain","origin_ar":"الحجاز، على الأرجح","origin_en":"Hejaz, likely","material_ar":"خشب مطلي أو محفور، بحسب الوصف التجريبي","material_en":"Painted or carved wood, based on the demo description","desc_ar":"لوح تعليمي مستوحى من الأبواب الخشبية المزخرفة في مدن الحجاز التاريخية. لا تنسب المنصة هذا النموذج إلى مبنى أو ورشة محددة.","desc_en":"An educational panel inspired by decorated wooden doors in historic Hejazi cities. The platform does not attribute this demo object to a specific building or workshop.","story_ar":"كان الباب في البيت الحجازي واجهةً بين الخاص والعام. تظهر فيه مهارة النجار وذائقة المالك وتأثيرات التجارة والحج. لكن الزخرفة وحدها لا تكفي لتحديد مدينة أو تاريخ دقيق، لذلك تبقى هذه القراءة احتمالية.","story_en":"In a Hejazi house, the door mediated between private and public life. It could express a carpenter’s skill, an owner’s taste, and influences carried through trade and pilgrimage. Decoration alone cannot establish a precise city or date, so this reading remains tentative.","facts_ar":["ازدهرت المشغولات الخشبية في مدن الحجاز التاريخية.","قد تجمع الزخارف بين أنماط محلية وتأثيرات وافدة.","يحتاج التأريخ الدقيق إلى توثيق مصدر القطعة وفحص مادتها."],"facts_en":["Woodworking flourished in historic Hejazi cities.","Decoration can combine local patterns with influences arriving through exchange.","Precise dating requires provenance records and material examination."],"timeline":[("قرون سابقة","Earlier centuries","تقاليد عمرانية","Architectural traditions","تراكمت تقنيات النجارة والزخرفة في البيئات الحضرية الحجازية.","Woodworking and decorative techniques accumulated in Hejazi urban environments."),("القرن 19","19th century","حركة واسعة للأشخاص والمواد","Movement of people and materials","أسهمت التجارة والحج في انتقال الأفكار والمواد والحرفيين.","Trade and pilgrimage supported the movement of ideas, materials, and craftspeople."),("القرن 21","21st century","جهود الحفظ","Conservation efforts","أصبحت الأبواب والعناصر الخشبية محورًا للتوثيق والترميم.","Doors and wooden elements became a focus of documentation and conservation.")]},
{"slug":"arabian-pottery-jar","title_ar":"جرة فخارية من الجزيرة العربية","title_en":"Arabian Pottery Jar","cat":"pottery","image":"/demo/pottery.svg","period_ar":"فترة غير محددة؛ نموذج تعليمي","period_en":"Unspecified period; educational model","date_ar":"لا تتوفر أدلة كافية","date_en":"Insufficient evidence","origin_ar":"الجزيرة العربية، كإطار تعليمي عام","origin_en":"Arabian Peninsula, as a broad educational context","material_ar":"فخار","material_en":"Ceramic","desc_ar":"نموذج تجريبي يوضح كيف تعرض رُوي حدود المعرفة عند غياب سياق الاكتشاف أو نتائج الفحص.","desc_en":"A demo model showing how Ruwi communicates knowledge limits when excavation context or scientific examination is unavailable.","story_ar":"قد تكون الجرة قد استخدمت للماء أو الحبوب أو النقل، لكن الشكل وحده لا يثبت وظيفة واحدة. لذلك تعرض رُوي عدة احتمالات وتفصل بينها وبين الحقائق التي تحتاج إلى مصدر أثري أو متحفي.","story_en":"The jar may have held water, grain, or goods in transit, but shape alone does not prove a single function. Ruwi therefore presents possibilities separately from facts requiring archaeological or museum documentation.","facts_ar":["الفخار مصدر مهم لدراسة تقنيات التصنيع والتبادل.","تساعد طبقات الموقع الأثري على التأريخ أكثر من الشكل وحده.","آثار الاستخدام قد تكشف وظيفة الوعاء عند فحصها مخبريًا."],"facts_en":["Pottery helps researchers study manufacturing techniques and exchange.","Archaeological layers usually support dating more strongly than shape alone.","Use-wear or residues can clarify function when scientifically examined."],"timeline":[("مرحلة التصنيع","Manufacture","تشكيل وحرق","Shaping and firing","صُنعت الأوعية الفخارية بتقنيات تختلف حسب المجتمع والموارد.","Ceramic vessels were made with techniques varying by community and resources."),("مرحلة الاستخدام","Use life","وظائف محتملة","Possible functions","قد تستخدم الأوعية للتخزين أو التقديم أو النقل، بحسب السياق.","Vessels may be used for storage, serving, or transport depending on context."),("مرحلة التوثيق","Documentation","من القطعة إلى الدليل","From object to evidence","تكتسب القطعة دلالة أدق عند ربطها بمصدر موثق وفحوص مناسبة.","The object gains more precise meaning when linked to provenance and suitable analysis.")]}
]
def run():
 db=SessionLocal()
 try:
  roles={n:db.query(Role).filter_by(name=n).first() or Role(name=n) for n in ['visitor','curator','admin']};db.add_all(list(roles.values()));db.flush()
  for email,pw,name,role in [(settings.demo_admin_email,settings.demo_admin_password,'Ruwi Administrator','admin'),(settings.demo_curator_email,settings.demo_curator_password,'Museum Curator','curator'),(settings.demo_visitor_email,settings.demo_visitor_password,'Demo Visitor','visitor')]:
   if not db.query(User).filter_by(email=email).first():db.add(User(email=email,password_hash=hash_password(pw),full_name=name,preferred_language='ar',roles=[roles[role]]))
  museum=db.query(Museum).first()
  if not museum:museum=Museum(name_ar='متحف رُوي التجريبي',name_en='Ruwi Demo Museum',city='Riyadh',description_ar='متحف افتراضي للتجربة.',description_en='A virtual museum for demonstration.');db.add(museum);db.flush()
  collection=db.query(Collection).first()
  if not collection:collection=Collection(museum_id=museum.id,name_ar='مختارات من التراث',name_en='Heritage Selections');db.add(collection);db.flush()
  cats={}
  for i,(slug,ar,en) in enumerate([('pottery','فخار','Pottery'),('metalwork','مشغولات معدنية','Metalwork'),('architecture','عناصر معمارية','Architectural Objects'),('manuscripts','مخطوطات','Manuscripts'),('textiles','منسوجات','Textiles')],1):
   c=db.query(ArtifactCategory).filter_by(slug=slug).first() or ArtifactCategory(id=i,slug=slug,name_ar=ar,name_en=en);db.add(c);cats[slug]=c
  db.flush()
  source=db.query(KnowledgeSource).first()
  if not source:source=KnowledgeSource(title='Ruwi Original Demo Heritage Notes',organization='Ruwi Demo Editorial Team',language='ar',trust_level='demo_curator_verified',verification_status='verified',usage_notes='Original bilingual content written specifically for the Ruwi demo.');db.add(source);db.flush()
  for d in DATA:
   if db.query(Artifact).filter_by(slug=d['slug']).first():continue
   a=Artifact(slug=d['slug'],collection_id=collection.id,category_id=cats[d['cat']].id,title_ar=d['title_ar'],title_en=d['title_en'],description_ar=d['desc_ar'],description_en=d['desc_en'],historical_period_ar=d['period_ar'],historical_period_en=d['period_en'],estimated_date_ar=d['date_ar'],estimated_date_en=d['date_en'],origin_ar=d['origin_ar'],origin_en=d['origin_en'],material_ar=d['material_ar'],material_en=d['material_en'],confidence=.88,verification_status='verified_demo',review_status='published',is_demo=True,is_published=True,image_url=d['image']);db.add(a);db.flush()
   db.add_all([ArtifactStory(artifact_id=a.id,language='ar',audience='general',title='حكاية القطعة',content=d['story_ar'],verified=True),ArtifactStory(artifact_id=a.id,language='en',audience='general',title='The Artifact Story',content=d['story_en'],verified=True)])
   for ar,en in zip(d['facts_ar'],d['facts_en']):db.add(ArtifactFact(artifact_id=a.id,text_ar=ar,text_en=en,verified=True))
   for i,t in enumerate(d['timeline']):db.add(TimelineEvent(artifact_id=a.id,year_label_ar=t[0],year_label_en=t[1],title_ar=t[2],title_en=t[3],description_ar=t[4],description_en=t[5],sort_order=i))
   db.add_all([ArtifactHotspot(artifact_id=a.id,x=.35,y=.35,label_ar='تفصيل بصري',label_en='Visual detail',description_ar='نقطة تفاعلية تشرح سمة مرئية دون افتراض غير موثق.',description_en='An interactive point explaining a visible feature without unsupported attribution.'),ArtifactHotspot(artifact_id=a.id,x=.67,y=.62,label_ar='المادة والتقنية',label_en='Material and technique',description_ar='التحديد الدقيق للمادة يحتاج إلى فحص مباشر.',description_en='Precise material identification requires direct examination.')])
   for lang,title,question,choices,correct,explanation in [('ar','اختبر معرفتك','ما العبارة الأكثر دقة عند غياب توثيق المصدر؟',['يمكن تحديد التاريخ بدقة من الشكل','يجب عرض الاحتمال وحدود المعرفة','كل القطع المتشابهة من الصانع نفسه','لا حاجة للمصادر'],1,'توضح رُوي الاحتمال وتفصل بينه وبين الحقائق الموثقة.'),('en','Check your knowledge','What is the most accurate approach when provenance is missing?',['Assign an exact date from shape','Present possibilities and knowledge limits','Assume similar objects share a maker','Sources are unnecessary'],1,'Ruwi distinguishes possibilities from verified claims.')]:
    q=Quiz(artifact_id=a.id,language=lang,title=title);db.add(q);db.flush();db.add(QuizQuestion(quiz_id=q.id,question=question,choices=choices,correct_index=correct,explanation=explanation,difficulty='easy'))
   db.add(ArtifactSourceReference(artifact_id=a.id,source_id=source.id,citation_label='Ruwi Demo Source 1',relevance=1.0))
  if not db.get(SystemSetting,'platform'):db.add(SystemSetting(key='platform',value={'demo_mode':settings.ai_provider=='none','supported_languages':['ar','en']},is_public=True))
  db.commit()
 finally:db.close()
if __name__=='__main__':run()
