import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'
import type { Artifact } from './types'

type Props={artifact:Artifact;onProgress?:(v:number)=>void}
type Drag=(dx:number,dy:number,p:THREE.Vector3)=>void
type Item={object:THREE.Object3D;label:string;drag?:Drag;tap?:()=>void}

const TITLES:Record<number,string>={
1:'موقع التنقيب — اقرأ الأثر من طبقاته',2:'مختبر البقايا — ماذا بقي داخل الوعاء؟',3:'محمية الماستودون — أعد بناء البيئة القديمة',4:'غابة الزمن — اقرأ مناخ الماضي من الخشب',5:'كهف حِمى — اكشف النقش بالضوء',6:'مختبر السقوط — رحلة النيزك إلى الأرض',7:'ورشة الفخار — شكّل الوعاء بيدك',8:'ورشة الحجر — اصنع حافة الأداة',9:'ورشة السهم — ركّب الأداة من مكوّناتها',10:'ورشة الصهر — نار، معدن، وقالب',11:'سوق المقايضة — أوجد وزن الصفقة',12:'مختبر الأدوات — نظّف وافحص الأثر',13:'مختبر الكتابة — اكشف الحروف بالضوء',14:'المذبح — أعد بناء المشهد الطقسي',15:'ورشة الآلية — افتح القفل بفهمه',16:'ورشة المصباح — الزيت والفتيل والنور',17:'المحبرة — اكتب أثرًا بالحبر',18:'ورشة الخنجر — اكشف الصناعة تحت الضوء',19:'ورشة العمارة — ابنِ التاج قطعة قطعة',20:'درب زبيدة — اعبر الطريق من محطة إلى محطة'}
const HINTS:Record<number,string>={
1:'اسحب الفرشاة فوق التربة. لا تبحث عن زر؛ ابحث عن الأثر تحت الطبقة.',2:'حرّك أداة الفحص داخل الوعاء ثم ارفعها نحو الضوء لرؤية البقايا.',3:'اسحب السحب عبر السماء وراقب تغيّر الماء والنبات والضباب حول الحيوان.',4:'مرّر الماسح على الجذع؛ زاوية الضوء تكشف حلقات النمو والسنوات الجافة.',5:'اسحب المشعل بمحاذاة الجدار، ثم اتبع الخط الذي يكشفه الضوء.',6:'أمسك النيزك واسحبه في السماء. جرّب زاوية دخول مختلفة وشاهد النتيجة.',7:'ضع يديك على الطين واسحب حوله. الشكل يتغير مع ضغطك واتجاهك.',8:'أمسك المطرقة واسحبها نحو الحجر. الضربة تغيّر الحافة وتُسقط شظايا صغيرة.',9:'التقط كل جزء وضعه في موضعه الصحيح؛ القطع تلتقط مكانها عندما تقترب.',10:'اسحب المنفاخ باستمرار. عندما يتوهج المعدن ارفع البوتقة واسكبها في القالب.',11:'انقل الأوزان بين الكفتين. الهدف هو توازن حقيقي، لا ملء مؤشر.',12:'حرّك الفرشاة ثم قرّب العدسة من السطح. الضوء يكشف آثار الاستخدام.',13:'حرّك المصباح بزاوية منخفضة؛ بعد ظهور الحروف تتبعها بإصبعك.',14:'انقل العناصر حول المذبح. المشهد والإضاءة يتغيران مع ترتيبك.',15:'حرّك الحلقة ببطء حتى تصطف الأسنان، ثم اسحب المزلاج.',16:'اسحب الزيت إلى الخزان، ثم ارفع الفتيل تدريجيًا. راقب الضوء وهو يملأ الغرفة.',17:'المس المحبرة أولًا، ثم اكتب على الورق بحركة يدك.',18:'اسحب الغمد، ثم مرّر ضوء الفحص على المقبض والزخرفة والمعدن.',19:'اسحب الأحجار إلى أماكنها. الوزن والموقع يحددان استقرار الطبقة.',20:'اسحب المسافر على الطريق. المحطات تكشف الماء والظل والمسافة.'}

const BACKPLATES:Record<string,string>={
workshop:'https://cdn.polyhaven.com/asset_img/primary/industrial_workshop_foundry.png?height=1200',
oldroom:'https://cdn.polyhaven.com/asset_img/primary/old_room.png?height=1200',
cave:'https://cdn.polyhaven.com/asset_img/primary/small_cave.png?height=1200',
desert:'https://cdn.polyhaven.com/asset_img/primary/rogland_sunset.png?height=1200',
night:'https://cdn.polyhaven.com/asset_img/primary/rogland_clear_night.png?height=1200',
workshop2:'https://cdn.polyhaven.com/asset_img/primary/university_workshop.png?height=1200',
road:'https://cdn.polyhaven.com/asset_img/primary/goegap_road.png?height=1200'}

function mat(c:string,r=.55,m=.05,e?:string,ei=0){return new THREE.MeshPhysicalMaterial({color:c,roughness:r,metalness:m,emissive:e?new THREE.Color(e):undefined,emissiveIntensity:ei,clearcoat:.25,clearcoatRoughness:.4})}
function box(w:number,h:number,d:number,c:string,r=.65,m=.03){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,r,m));o.castShadow=true;o.receiveShadow=true;return o}
function cyl(r:number,h:number,c:string,rgh=.55,m=.03){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,64),mat(c,rgh,m));o.castShadow=true;o.receiveShadow=true;return o}
function lathe(points:[number,number][],c:string,r=.5,m=.02){const o=new THREE.Mesh(new THREE.LatheGeometry(points.map(([x,y])=>new THREE.Vector2(x,y)),64),mat(c,r,m));o.castShadow=true;o.receiveShadow=true;return o}
function sph(r:number,c:string,rgh=.45,m=.03){const o=new THREE.Mesh(new THREE.SphereGeometry(r,48,32),mat(c,rgh,m));o.castShadow=true;o.receiveShadow=true;return o}
function plane(w:number,h:number,c:string,r=.9){const o=new THREE.Mesh(new THREE.PlaneGeometry(w,h),mat(c,r));o.receiveShadow=true;return o}
function particles(scene:THREE.Scene,count:number,color:string,spread=7,height=3,size=.015){const a=new Float32Array(count*3);for(let i=0;i<count;i++){a[i*3]=(Math.random()-.5)*spread;a[i*3+1]=(Math.random()-.5)*height;a[i*3+2]=(Math.random()-.5)*spread*.5}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(a,3));const p=new THREE.Points(g,new THREE.PointsMaterial({color,size,transparent:true,opacity:.35,depthWrite:false}));scene.add(p);return p}
function sound(kind:string='click'){try{const AC=window.AudioContext||(window as any).webkitAudioContext;if(!AC)return;const a=new AC(),o=a.createOscillator(),g=a.createGain(),freqs:Record<string,number>={fire:70,stone:115,metal:280,water:430,wood:160,air:85,ink:210,click:620};o.type='triangle';o.frequency.value=freqs[kind]||220;g.gain.setValueAtTime(.0001,a.currentTime);g.gain.exponentialRampToValueAtTime(.04,a.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.2);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.21)}catch{}}

function addArch(scene:THREE.Scene,x:number,z:number,w:number,h:number,color:string){const shape=new THREE.Shape();shape.moveTo(-w/2,0);shape.lineTo(-w/2,h*.55);shape.absarc(0,h*.55,w/2,Math.PI,0,false);shape.lineTo(w/2,0);shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:.16,bevelEnabled:true,bevelSize:.035,bevelThickness:.03});const o=new THREE.Mesh(geo,mat(color,.9));o.position.set(x, -1.42,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
function addWorkbench(scene:THREE.Scene,x:number,z:number,scale=1){const g=new THREE.Group();const top=box(2.7*scale,.18,.95*scale,'#4b3021',.82,.04);top.position.y=-.35;g.add(top);for(const sx of [-1,1])for(const sz of [-1,1]){const leg=box(.12*scale,1.1*scale,.12*scale,'#2c1c14',.8,.03);leg.position.set(sx*1.12*scale,-.9,sz*.32*scale);g.add(leg)}g.position.set(x,-.55,z);scene.add(g);return g}
function addShelf(scene:THREE.Scene,x:number,z:number){const g=new THREE.Group();const back=box(1.9,2.6,.12,'#30241d',.88);back.position.y=-.05;g.add(back);for(let i=0;i<4;i++){const s=box(1.9,.08,.5,'#5b3b28',.78);s.position.set(0,-1.0+i*.62,.1);g.add(s)}g.position.set(x,0,z);scene.add(g);return g}
function addLamp(scene:THREE.Scene,x:number,y:number,z:number,color='#ffb45c'){const light=new THREE.PointLight(color,3.2,6);light.position.set(x,y,z);light.castShadow=true;scene.add(light);const shade=lathe([[.03,0],[.18,.05],[.32,.22],[.24,.28],[.08,.3]],'#8d6a3e',.6,.25);shade.position.set(x,y-.05,z);scene.add(shade);const bulb=new THREE.Mesh(new THREE.SphereGeometry(.08,24,16),new THREE.MeshBasicMaterial({color}));bulb.position.set(x,y-.2,z);scene.add(bulb);return light}
function buildEnvironment(scene:THREE.Scene,kind:string){
 const floor=plane(9,8,'#1b1a17',.98);floor.rotation.x=-Math.PI/2;floor.position.y=-1.48;scene.add(floor)
 const wall=plane(9,6,'#24221e',.92);wall.position.set(0,1.5,-3.2);scene.add(wall)
 const side=plane(6,6,'#1b1b18',.95);side.rotation.y=Math.PI/2;side.position.set(-4.5,1.5,0);scene.add(side)
 if(kind==='cave'){(floor.material as THREE.MeshPhysicalMaterial).color.set('#3c342a');(wall.material as THREE.MeshPhysicalMaterial).color.set('#3b332b');addArch(scene,-1.6,-3.0,3.4,3.7,'#4c4338');addArch(scene,1.8,-3.05,2.2,3.1,'#3c352e')}
 else if(kind==='desert'){(floor.material as THREE.MeshPhysicalMaterial).color.set('#6b5237');(wall.material as THREE.MeshPhysicalMaterial).color.set('#765b3c');for(let i=0;i<12;i++){const rock=sph(.12+Math.random()*.25,'#5c4632',.95);rock.position.set((Math.random()-.5)*8,-1.25,(Math.random()-.5)*4-1);scene.add(rock)} }
 else if(kind==='oldroom'){(wall.material as THREE.MeshPhysicalMaterial).color.set('#3b3028');addArch(scene,-1.6,-3.0,3.3,3.8,'#5a4637');addArch(scene,1.8,-3.05,2.2,3.2,'#4b3a2e');addLamp(scene,0,1.9,-2.7,'#f0c77b')}
 else if(kind==='workshop'||kind==='workshop2'){(wall.material as THREE.MeshPhysicalMaterial).color.set('#303331');addWorkbench(scene,-1.2,-.5,.95);addShelf(scene,2.9,-2.7);addLamp(scene,-2.5,1.7,-1.4,'#ffd08b');addLamp(scene,2.3,1.9,-2.5,'#d8e6ff')}
 else if(kind==='night'){(floor.material as THREE.MeshPhysicalMaterial).color.set('#201b18');(wall.material as THREE.MeshPhysicalMaterial).color.set('#11151a');for(let i=0;i<40;i++){const star=sph(.018,'#d9e5ff',.2);star.position.set((Math.random()-.5)*9,Math.random()*4-0.3,-2.9);scene.add(star)} }
 else if(kind==='road'){(floor.material as THREE.MeshPhysicalMaterial).color.set('#6e5b46');(wall.material as THREE.MeshPhysicalMaterial).color.set('#81745f');addArch(scene,0,-3.05,5.8,3.5,'#927c5f')}
 for(let i=0;i<3;i++){const column=cyl(.16,4.6,'#51483e',.9);column.position.set(-3.6+i*3.6,.8,-2.9);scene.add(column)}
}

export default function ExperienceWorld({artifact,onProgress}:Props){
 const host=useRef<HTMLDivElement>(null);const [progress,setProgress]=useState(.03);const [message,setMessage]=useState('المشهد ينتظر لمستك');const pRef=useRef(.03);pRef.current=progress
 const setP=(v:number,m?:string)=>{const n=THREE.MathUtils.clamp(v,0,1);pRef.current=n;setProgress(n);onProgress?.(n);if(m)setMessage(m)}
 useEffect(()=>{const el=host.current;if(!el)return;let dead=false;const scene=new THREE.Scene();scene.background=new THREE.Color('#090b0a');const camera=new THREE.PerspectiveCamera(44,1,.05,100);camera.position.set(0,.2,8.4);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.setClearAlpha(0);el.appendChild(renderer.domElement)
 const backplate=BACKPLATES[artifact.id===5||artifact.id===3?'cave':artifact.id===6?'night':artifact.id===20?'road':[10,12,15,16,17,18,19].includes(artifact.id)?'workshop':artifact.id===1||artifact.id===4||artifact.id===11?'oldroom':'workshop2'];el.style.backgroundImage=`linear-gradient(rgba(5,8,7,.48),rgba(5,8,7,.72)),url(${backplate})`;el.style.backgroundSize='cover';el.style.backgroundPosition='center';el.style.backgroundRepeat='no-repeat'
 const hemi=new THREE.HemisphereLight('#fff5dc','#243c31',2.0);scene.add(hemi);const key=new THREE.DirectionalLight('#fff0ce',4.2);key.position.set(3,6,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const fill=new THREE.DirectionalLight('#8fc6aa',1.4);fill.position.set(-5,3,2);scene.add(fill);buildEnvironment(scene,artifact.id===5||artifact.id===3?'cave':artifact.id===6?'night':artifact.id===20?'road':[10,12,15,16,17,18,19].includes(artifact.id)?'workshop':artifact.id===1||artifact.id===4||artifact.id===11?'oldroom':'workshop2')
 const root=new THREE.Group();scene.add(root);const interact:Item[]=[];const add=<T extends THREE.Object3D>(o:T,label:string,drag?:Drag,tap?:()=>void)=>{root.add(o);interact.push({object:o,label,drag,tap});return o}
 let update=(t:number)=>{};let dust:THREE.Points|undefined
 // 1 excavation
 if(artifact.id===1){const table=add(box(3.8,.24,2.2,'#6a4932',.82),'منصة التنقيب');table.position.set(-.6,-1.12,.15);for(let i=0;i<5;i++){const layer=add(box(3.5,.075,2.0,['#9a7650','#846343','#6d543e','#564436','#3e332c'][i],1),'طبقة أثرية');layer.position.set(-.6,-.96-i*.09,.1)}const brush=add(cyl(.055,1.05,'#8c5d35',.8),'فرشاة');brush.rotation.z=-.75;brush.position.set(-2,.15,.5);const fossil=add(lathe([[.02,-.28],[.13,-.24],[.18,-.05],[.12,.22],[.04,.28]],'#c6ab82',.9),'أثر');fossil.rotation.z=Math.PI/2;fossil.position.set(-.35,-.55,.5);interact[interact.length-1].drag=(dx,dy)=>{brush.position.x=THREE.MathUtils.clamp(brush.position.x+dx*.009,-2.3,1.2);brush.position.z=THREE.MathUtils.clamp(brush.position.z-dy*.008,-.2,1.2);const q=Math.min(1,pRef.current+(Math.abs(dx)+Math.abs(dy))*.0018);fossil.scale.setScalar(.6+.8*q);setP(q,q>.86?'اكتمل كشف الأثر.':'استمر في إزالة التربة بالفرشاة.');sound('stone')};dust=particles(scene,260,'#bca27c',4.8,1.6,.014);update=t=>{dust!.rotation.y+=.0008;brush.rotation.z=-.75+Math.sin(t*2)*.04}}
 // 2 residue lab
 else if(artifact.id===2){const table=add(box(3.7,.22,2.0,'#513a2b',.82),'طاولة المختبر');table.position.set(-.6,-1.12,.15);const vessel=add(lathe([[.22,-.6],[.55,-.48],[.72,-.05],[.65,.45],[.42,.62],[.18,.55]],'#9d7b58',.52),'وعاء فخاري');vessel.position.set(-.7,-.4,.2);const dish=add(new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,.05,64),mat('#6f4b2d',.18)),'عينة');dish.position.set(-.7,.23,.2);const pip=add(cyl(.035,1.25,'#b8a58b',.28,.65),'أداة الفحص');pip.rotation.z=-.55;pip.position.set(-2,.35,.7);const lens=add(new THREE.Mesh(new THREE.TorusGeometry(.22,.035,24,64),mat('#c8d0c8',.15,.75)),'عدسة');lens.position.set(.7,.2,.65);interact[interact.length-1].drag=(dx,dy)=>{pip.position.x=THREE.MathUtils.clamp(pip.position.x+dx*.009,-2.3,.4);pip.position.z=THREE.MathUtils.clamp(pip.position.z-dy*.008,-.2,1.4);const q=Math.min(1,pRef.current+(Math.abs(dx)+Math.abs(dy))*.0017);lens.scale.setScalar(.8+1.1*q);setP(q,q>.84?'ظهرت البقايا الدقيقة: قار وأصداف.':'حرّك أداة الفحص داخل الوعاء.');sound('water')}}
 // 3 paleo climate
 else if(artifact.id===3){const ground=add(box(4.5,.28,2.8,'#665440',.98),'الأرض القديمة');ground.position.set(-.5,-1.12,.1);const water=add(new THREE.Mesh(new THREE.CircleGeometry(1.35,64),new THREE.MeshPhysicalMaterial({color:'#4d8a8e',roughness:.12,transmission:.2,transparent:true,opacity:.82})),'الماء');water.rotation.x=-Math.PI/2;water.position.set(-.3,-.96,.15);const plantGroup=new THREE.Group();root.add(plantGroup);for(let i=0;i<16;i++){const stem=cyl(.025,.7+Math.random()*.6,'#527457',.95);stem.position.set(-2.1+Math.random()*3.2,-.55,Math.random()*1.1);stem.rotation.z=(Math.random()-.5)*.4;plantGroup.add(stem)}const cloud=add(sph(.55,'#c4c9c0',.9),'سحابة');cloud.scale.set(1.8,.65,1);cloud.position.set(-1.4,1.1,.1);interact[interact.length-1].drag=(dx)=>{cloud.position.x=THREE.MathUtils.clamp(cloud.position.x+dx*.008,-2.4,1.2);const q=Math.min(1,pRef.current+Math.abs(dx)*.0015);water.scale.set(1+.35*q,1+.35*q,1);plantGroup.scale.y=1+.25*q;setP(q,q>.86?'اكتملت إعادة بناء البيئة القديمة.':'حرّك السحب عبر السماء.')};dust=particles(scene,100,'#b9c7b8',4,2,.012)}
 // 4 tree rings
 else if(artifact.id===4){const stump=add(lathe([[.5,-.7],[.58,-.5],[.65,.1],[.6,.55],[.48,.7]],'#5b3822',.88),'جذع متحجر');stump.position.set(-.8,-.55,.2);for(let i=0;i<7;i++){const ring=add(new THREE.Mesh(new THREE.TorusGeometry(.17+i*.07,.018,16,64),new THREE.MeshPhysicalMaterial({color:'#c59a62',roughness:.75})),'حلقة نمو');ring.rotation.x=Math.PI/2;ring.position.set(-.8,.17,.2);ring.scale.y=.7}const scanner=add(new THREE.Mesh(new THREE.TorusGeometry(.3,.035,20,64),mat('#9fe0bf',.25,.35,'#6aa889',.2)),'ماسح الحلقات');scanner.position.set(-2,.3,.6);interact[interact.length-1].drag=(dx,dy)=>{scanner.position.x=THREE.MathUtils.clamp(scanner.position.x+dx*.009,-2.3,1);scanner.position.y=THREE.MathUtils.clamp(scanner.position.y-dy*.009,-.7,1.3);const q=Math.min(1,pRef.current+(Math.abs(dx)+Math.abs(dy))*.0017);setP(q,q>.86?'اكتملت قراءة حلقات النمو.':'مرّر الماسح فوق الجذع.');sound('wood')}}
 // 5 cave engraving
 else if(artifact.id===5){const wall=add(box(4.4,3.0,.35,'#4a4036',.95),'جدار الكهف');wall.position.set(-.4,.05,.1);const flame=add(new THREE.PointLight('#ff9d43',2.5,5),'المشعل');flame.position.set(-2,.2,.6);const torch=add(box(.12,.9,.12,'#6a3d22',.9),'المشعل');torch.position.set(-2,-.1,.5);const mark=add(new THREE.Mesh(new THREE.TorusGeometry(.7,.035,16,64),new THREE.MeshBasicMaterial({color:'#b89c6d',transparent:true,opacity:.12})),'النقش');mark.position.set(-.4,.45,.27);mark.scale.set(1.3,.7,1);interact[interact.length-1].drag=(dx,dy)=>{torch.position.x=THREE.MathUtils.clamp(torch.position.x+dx*.009,-2.4,1.5);torch.position.y=THREE.MathUtils.clamp(torch.position.y-dy*.009,-.8,1.2);flame.position.copy(torch.position);flame.position.y+=.35;const q=Math.min(1,pRef.current+(Math.abs(dx)+Math.abs(dy))*.0017);(mark.material as THREE.MeshBasicMaterial).opacity=.08+.72*q;setP(q,q>.86?'ظهر النقش كاملًا تحت الضوء المائل.':'حرّك المشعل بمحاذاة الجدار.');sound('fire')}}
 // 6 meteor
 else if(artifact.id===6){const earth=add(new THREE.Mesh(new THREE.SphereGeometry(1.55,64,48),mat('#4d6652',.95)),'الأرض');earth.position.set(.6,-.65,-.4);const atmosphere=add(new THREE.Mesh(new THREE.SphereGeometry(1.7,48,32),new THREE.MeshBasicMaterial({color:'#5c9bd1',transparent:true,opacity:.08,side:THREE.BackSide})),'الغلاف الجوي');atmosphere.position.copy(earth.position);const meteor=add(sph(.24,'#5a5148',.72,.15),'النيزك');meteor.position.set(-2.6,1.7,.5);const trail=particles(scene,90,'#ff9b4a',2.5,1.5,.025);interact[interact.length-1].drag=(dx,dy)=>{meteor.position.x=THREE.MathUtils.clamp(meteor.position.x+dx*.01,-2.8,1.8);meteor.position.y=THREE.MathUtils.clamp(meteor.position.y-dy*.01,-.9,2.1);const q=Math.min(1,pRef.current+((Math.abs(dx)+Math.abs(dy))*.0014));const heat=Math.max(0,(q-.35)/.65);meteor.scale.setScalar(1+heat*.8);trail.position.copy(meteor.position);setP(q,q>.88?'اصطدم النيزك بالأرض.':'اسحب النيزك نحو الغلاف الجوي.');sound('fire')}}
 // 7 pottery wheel
 else if(artifact.id===7){addWorkbench(scene,-.6,-.2,1);const wheel=add(new THREE.Mesh(new THREE.CylinderGeometry(.85,.85,.12,64),mat('#5f625e',.72)),'عجلة الفخار');wheel.rotation.x=0;wheel.position.set(-.7,-.7,.15);const clay=add(lathe([[.05,-.22],[.25,-.18],[.38,-.08],[.42,.08],[.3,.22],[.08,.28]],'#9b6a45',.78),'الطين');clay.position.set(-.7,-.55,.15);interact[interact.length-1].drag=(dx,dy)=>{const q=Math.min(1,pRef.current+(Math.abs(dx)+Math.abs(dy))*.0018);wheel.rotation.y+=dx*.015;clay.scale.x=1+.65*q;clay.scale.y=1-.22*q;clay.scale.z=1+.35*q;setP(q,q>.9?'اكتمل تشكيل الوعاء.':'اسحب إصبعك حول الطين لتشكيله.');sound('wood')}}
 // 8 stone knapping
 else if(artifact.id===8){const anvil=add(box(2.3,.45,1.3,'#5c5d58',.72,.25),'حجر السندان');anvil.position.set(-.6,-.95,.2);const core=add(new THREE.Mesh(new THREE.IcosahedronGeometry(.7,2),mat('#6d655b',.82)),'حجر خام');core.position.set(-.6,-.25,.2);const hammer=add(cyl(.11,1.0,'#6f4b31',.85),'مطرقة');hammer.position.set(-2,.6,.7);hammer.rotation.z=-.65;interact[interact.length-1].drag=(dx,dy)=>{hammer.position.x=THREE.MathUtils.clamp(hammer.position.x+dx*.011,-2.3,.6);hammer.position.y=THREE.MathUtils.clamp(hammer.position.y-dy*.011,-.5,1.5);const hit=Math.max(0,1-Math.hypot(hammer.position.x+.6,hammer.position.y-.1));const q=Math.min(1,pRef.current+hit*.018);core.scale.set(1-.22*q,1-.1*q,1-.22*q);setP(q,q>.9?'اكتملت الحافة الحادة.':'وجّه المطرقة إلى الحافة الخارجية للحجر.');if(hit>.8)sound('stone')}}
 // 9 arrow assembly
 else if(artifact.id===9){const table=addWorkbench(scene,-.5,-.3,1);void table;const shaft=add(cyl(.035,2.6,'#9a6a3e',.78),'ساق السهم');shaft.rotation.z=Math.PI/2;shaft.position.set(-.7,-.45,.3);const head=add(new THREE.Mesh(new THREE.ConeGeometry(.17,.48,4),mat('#5b5d59',.35,.75)),'رأس السهم');head.rotation.z=-Math.PI/2;head.position.set(-2,.25,.3);const feather=add(new THREE.Mesh(new THREE.ShapeGeometry(new THREE.Shape()),mat('#a16b3d',.8)),'ريشة');feather.position.set(.4,-.2,.3);const wrap=add(cyl(.055,.25,'#9c6c45',.85),'رباط');wrap.position.set(.5,-.45,.3);interact[interact.length-1].drag=(dx,dy)=>{head.position.x=THREE.MathUtils.clamp(head.position.x+dx*.01,-2,.3);const d=Math.abs(head.position.x-(-1.35));const q=Math.min(1,pRef.current+(Math.max(0,1-d/.7))*0.015);if(d<.16)head.position.x=-1.35;setP(q,q>.9?'اكتمل رأس السهم ورباطه.':'اسحب رأس السهم إلى مقدمة الساق.');sound('metal')}}
 // 10 smelting
 else if(artifact.id===10){const forge=add(box(2.4,1.5,1.8,'#3a3028',.9),'فرن الصهر');forge.position.set(-.6,-.55,.1);const mouth=add(new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,.15,48),new THREE.MeshPhysicalMaterial({color:'#241b17',roughness:.95,emissive:'#ff5a1f',emissiveIntensity:.2})),'فتحة الفرن');mouth.rotation.x=Math.PI/2;mouth.position.set(-.6,-.2,1.0);const bellows=add(box(.8,.35,.5,'#6a3f28',.8),'المنفاخ');bellows.position.set(-2,-.15,.5);const cruc=add(lathe([[.1,-.3],[.28,-.25],[.34,.12],[.2,.28],[.08,.25]],'#7a7770',.38,.75),'البوتقة');cruc.position.set(.9,-.7,.45);const metal=add(new THREE.Mesh(new THREE.SphereGeometry(.28,32,24),new THREE.MeshPhysicalMaterial({color:'#b84c1e',roughness:.2,metalness:.65,emissive:'#ff5a14',emissiveIntensity:.5})),'المعدن');metal.position.set(.9,-.35,.45);const fire=new THREE.PointLight('#ff6a2a',1.5,4);fire.position.set(-.6,-.1,.9);scene.add(fire);const sparks=particles(scene,120,'#ffb05b',2.5,2,.025);interact[interact.length-1].drag=(dx)=>{bellows.position.x=THREE.MathUtils.clamp(bellows.position.x+dx*.01,-2.2,-.4);const q=Math.min(1,pRef.current+Math.abs(dx)*.002);fire.intensity=1.5+6*q;metal.scale.setScalar(.7+1.2*q);(mouth.material as THREE.MeshPhysicalMaterial).emissiveIntensity=.2+1.8*q;setP(q,q>.9?'وصل المعدن إلى حالة الانصهار.':'حرّك المنفاخ لرفع حرارة الفرن.');sound('air')};update=t=>{sparks.rotation.y+=.01;fire.intensity+=Math.sin(t*12)*.12}}
 // 11 scale
 else if(artifact.id===11){const beam=add(box(2.5,.08,.12,'#9d7d49',.55,.5),'عارضة الميزان');beam.position.set(-.6,-.2,.3);const fulcrum=add(lathe([[.05,-.7],[.3,-.55],[.36,.0],[.22,.25],[.05,.2]],'#6b5940',.78),'نقطة الارتكاز');fulcrum.position.set(-.6,-.95,.3);const pans:THREE.Mesh[]=[];for(const x of [-1.6,.4]){const pan=add(new THREE.Mesh(new THREE.CylinderGeometry(.55,.5,.08,64),mat('#a28c63',.55,.45)),'كفة');pan.position.set(x,-.65,.3);pans.push(pan)}const weights:THREE.Mesh[]=[];for(let i=0;i<3;i++){const w=add(cyl(.14+.04*i,.18+.05*i,'#77736a',.3,.8),'وزن');w.position.set(-2+i*.25,.2,.5);weights.push(w)}interact[interact.length-1].drag=(dx,dy)=>{const w=weights[weights.length-1];w.position.x=THREE.MathUtils.clamp(w.position.x+dx*.009,-2,.4);const q=Math.min(1,pRef.current+Math.abs(dx)*.0012);beam.rotation.z=(w.position.x+.6)*-.18;pans[0].position.y=-.65+Math.sin(beam.rotation.z)*.7;pans[1].position.y=-.65-Math.sin(beam.rotation.z)*.7;setP(q,Math.abs(beam.rotation.z)<.025?'الميزان متوازن.':'انقل الوزن حتى تتقارب الكفتان.');sound('metal')}}
 // 12 tool inspection
 else if(artifact.id===12){addWorkbench(scene,-.5,-.3,1);const tool=add(lathe([[.05,-.8],[.16,-.65],[.18,.1],[.28,.45],[.1,.75]],'#77776f',.35,.85),'الأداة');tool.position.set(-.6,-.3,.35);const brush=add(cyl(.06,.9,'#8b5c37',.85),'فرشاة');brush.position.set(-2,.2,.6);const lens=add(new THREE.Mesh(new THREE.TorusGeometry(.32,.05,24,64),mat('#aab9b0',.18,.8)),'عدسة');lens.position.set(1.2,.3,.55);interact[interact.length-1].drag=(dx,dy)=>{brush.position.x=THREE.MathUtils.clamp(brush.position.x+dx*.009,-2.3,.2);const q=Math.min(1,pRef.current+(Math.abs(dx)+Math.abs(dy))*.0017);lens.scale.setScalar(.8+1.2*q);setP(q,q>.88?'اكتملت قراءة سطح الأداة.':'نظّف السطح ثم قرّب العدسة.');sound('stone')}}
 // 13 calligraphy
 else if(artifact.id===13){addWorkbench(scene,-.5,-.3,1);const paper=add(box(2.8,.03,1.7,'#e8dcc0',.98),'ورق');paper.position.set(-.5,-.55,.35);const lamp=addLamp(scene,1.3,.8,.45,'#f5c77b');const pen=add(cyl(.025,.9,'#3a2720',.5),'قلم');pen.rotation.z=-.7;pen.position.set(-1.9,.0,.6);const strokes=new THREE.Group();root.add(strokes);interact[interact.length-1].drag=(dx,dy)=>{pen.position.x=THREE.MathUtils.clamp(pen.position.x+dx*.009,-2.2,1.1);pen.position.z=THREE.MathUtils.clamp(pen.position.z-dy*.009,-.2,1.2);const q=Math.min(1,pRef.current+(Math.abs(dx)+Math.abs(dy))*.0013);if(q>.12){const mark=new THREE.Mesh(new THREE.TorusGeometry(.08,.014,8,28),new THREE.MeshBasicMaterial({color:'#241c25',transparent:true,opacity:.72}));mark.position.copy(pen.position);mark.position.y=-.5;strokes.add(mark)}lamp.intensity=2+4*q;setP(q,q>.9?'اكتملت صفحة الخط.':'اكتب بالحركة نفسها التي يكتب بها الخطاط.');sound('ink')}}
 // 14 altar
 else if(artifact.id===14){const altar=add(box(1.8,1.0,1.6,'#8a735a',.95),'المذبح');altar.position.set(-.7,-.6,.15);const items:THREE.Mesh[]=[];for(let i=0;i<4;i++){const o=add(lathe([[.03,-.15],[.1,-.1],[.15,.08],[.08,.18]],['#9a6b45','#777b76','#b49a65','#6c725f'][i],.75),'عنصر طقسي');o.position.set(-2+i*.55,-.1,.45);items.push(o);interact[interact.length-1].drag=(dx,dy)=>{o.position.x=THREE.MathUtils.clamp(o.position.x+dx*.009,-2.3,.8);o.position.z=THREE.MathUtils.clamp(o.position.z-dy*.009,-.5,1);const q=Math.min(1,pRef.current+(Math.abs(dx)+Math.abs(dy))*.0015);setP(q,q>.9?'اكتمل ترتيب المشهد حول المذبح.':'انقل العناصر حول المذبح.');sound('stone')}}const light=new THREE.PointLight('#d7b56d',1.2,4);light.position.set(-.7,.6,.4);scene.add(light);update=t=>{light.intensity=1.1+Math.sin(t*1.2)*.2}}
 // 15 lock mechanism
 else if(artifact.id===15){const base=add(box(2.8,.3,1.8,'#4a4740',.42,.72),'قاعدة الآلية');base.position.set(-.5,-.95,.2);const ring=add(new THREE.Mesh(new THREE.TorusGeometry(.65,.14,32,80),mat('#8d8b82',.28,.85)),'الحلقة');ring.position.set(-.6,-.05,.45);const gear=new THREE.Mesh(new THREE.CylinderGeometry(.48,.48,.18,20),mat('#55534d',.3,.8));gear.rotation.x=Math.PI/2;gear.position.set(-.6,-.05,.42);root.add(gear);const pin=add(cyl(.09,1.0,'#a08a5d',.35,.8),'المزلاج');pin.position.set(.9,-.3,.5);interact[interact.length-1].drag=(dx)=>{ring.rotation.z+=dx*.012;const q=Math.min(1,pRef.current+Math.abs(dx)*.0018);gear.rotation.z=ring.rotation.z*2;setP(q,q>.84?'تطابقت الأسنان. اسحب المزلاج.':'حرّك الحلقة ببطء حتى تصطف الأسنان.');sound('metal')};interact.push({object:pin,label:'المزلاج',drag:(dx)=>{if(pRef.current<.78)return;pin.position.x=THREE.MathUtils.clamp(pin.position.x+dx*.01,.2,1.8);setP(Math.min(1,pRef.current+.03),pRef.current>.95?'انفتحت الآلية.':'اسحب المزلاج للخلف.');sound('click')}})}
 // 16 lamp
 else if(artifact.id===16){addWorkbench(scene,-.5,-.3,1);const lamp=add(lathe([[.05,-.45],[.35,-.35],[.55,-.1],[.48,.28],[.25,.45],[.08,.42]],'#7d6a52',.65,.18),'مصباح');lamp.position.set(-.6,-.5,.3);const oil=add(new THREE.Mesh(new THREE.CylinderGeometry(.4,.4,.05,64),new THREE.MeshPhysicalMaterial({color:'#b47d35',roughness:.1,transparent:true,opacity:.8})),'الزيت');oil.position.set(-.6,-.08,.3);const jug=add(lathe([[.05,-.3],[.18,-.28],[.24,.0],[.17,.32],[.05,.38]],'#7b5137',.78),'قنينة الزيت');jug.position.set(-2,.1,.5);const wick=add(cyl(.035,.5,'#30251d',.9),'الفتيل');wick.position.set(-.6,.1,.3);const flame=add(new THREE.Mesh(new THREE.ConeGeometry(.16,.5,32),new THREE.MeshBasicMaterial({color:'#ff9d3e',transparent:true,opacity:.9})),'اللهب');flame.position.set(-.6,.5,.3);const light=add(new THREE.PointLight('#ffad55',.8,2),'ضوء المصباح');light.position.copy(flame.position);interact[interact.length-1].drag=(dx,dy)=>{jug.position.x=THREE.MathUtils.clamp(jug.position.x+dx*.009,-2.3,.1);const q=Math.min(1,pRef.current+Math.abs(dx)*.0014);oil.scale.y=.2+1.7*q;setP(q,q>.55?'ارفع الفتيل بعد ملء الخزان.':'اسحب الزيت إلى خزان المصباح.');sound('water')};interact[interact.length-2].drag=(dx,dy)=>{if(pRef.current<.45)return;wick.position.y=THREE.MathUtils.clamp(wick.position.y-dy*.009,-.02,.5);const q=Math.min(1,pRef.current+Math.abs(dy)*.002);flame.scale.set(1+.5*q,.5+2*q,1+.5*q);light.intensity=1+8*q;setP(q,q>.9?'اشتعل المصباح وانتشر الضوء في الغرفة.':'ارفع الفتيل تدريجيًا.');sound('fire')};update=t=>{flame.rotation.z=Math.sin(t*8)*.05}}
 // 17 ink
 else if(artifact.id===17){addWorkbench(scene,-.5,-.3,1);const paper=add(box(2.6,.03,1.6,'#e8dcc0',.98),'الورق');paper.position.set(-.4,-.55,.4);const ink=add(lathe([[.05,-.2],[.2,-.18],[.27,.0],[.18,.22],[.05,.25]],'#4d3328',.78),'المحبرة');ink.position.set(-2,-.35,.55);const pen=add(cyl(.025,.95,'#2b2c2d',.35,.45),'القلم');pen.position.set(-1.4,.05,.6);const strokes=new THREE.Group();root.add(strokes);interact[interact.length-1].drag=(dx,dy)=>{pen.position.x=THREE.MathUtils.clamp(pen.position.x+dx*.009,-2.2,1.2);pen.position.z=THREE.MathUtils.clamp(pen.position.z-dy*.009,-.1,1.2);const q=Math.min(1,pRef.current+(Math.abs(dx)+Math.abs(dy))*.0014);if(q>.12){const mark=new THREE.Mesh(new THREE.TorusGeometry(.07,.012,8,24),new THREE.MeshBasicMaterial({color:'#251e27',transparent:true,opacity:.72}));mark.position.copy(pen.position);mark.position.y=-.54;strokes.add(mark)}setP(q,q>.88?'اكتملت صفحة الحبر.':'اكتب على الورق بعد لمس المحبرة.');sound('ink')}}
 // 18 dagger inspection
 else if(artifact.id===18){addWorkbench(scene,-.5,-.3,1);const blade=add(new THREE.Mesh(new THREE.ShapeGeometry(new THREE.Shape()),mat('#aeb2af',.18,.95)),'النصل');blade.scale.set(1,3,1);blade.position.set(-.5,-.2,.4);const sheath=add(lathe([[.08,-.9],[.16,-.75],[.18,.65],[.1,.9]],'#51362a',.62,.12),'الغمد');sheath.position.set(-1.1,-.1,.5);const light=add(new THREE.PointLight('#ffe7a9',2.4,5),'ضوء الفحص');light.position.set(-2,.4,.5);const lamp=add(new THREE.Mesh(new THREE.SphereGeometry(.08,24,16),new THREE.MeshBasicMaterial({color:'#ffe7a9'})),'مصباح');lamp.position.copy(light.position);interact[interact.length-1].drag=(dx)=>{light.position.x=THREE.MathUtils.clamp(light.position.x+dx*.009,-2.3,1.2);lamp.position.copy(light.position);const q=Math.min(1,pRef.current+Math.abs(dx)*.0015);setP(q,q>.86?'ظهرت تفاصيل المعدن والزخرفة تحت الضوء.':'حرّك الضوء بزاوية منخفضة.');sound('metal')};interact.push({object:sheath,label:'الغمد',drag:(dx)=>{sheath.position.x=THREE.MathUtils.clamp(sheath.position.x+dx*.009,-1.8,.2);const q=Math.min(1,pRef.current+Math.abs(dx)*.0018);setP(q,q>.7?'انكشف النصل. افحص تفاصيله بالضوء.':'اسحب الغمد عن النصل.');sound('metal')}})}
 // 19 architecture
 else if(artifact.id===19){const plinth=add(box(2.5,.28,1.9,'#7f705c',.9),'قاعدة العمود');plinth.position.set(-.6,-1.05,.25);const shaft=add(lathe([[.25,-1.2],[.3,-1.0],[.3,.8],[.4,1.05],[.25,1.2]],'#9b8b74',.92),'بدن العمود');shaft.position.set(-.6,-.2,.25);const blocks:THREE.Mesh[]=[];for(let i=0;i<5;i++){const b=add(box(.75-.06*i,.18,.75-.06*i,'#b2a38c',.92),'حجر بناء');b.position.set(-2+i*.45,-.85,.35);blocks.push(b);interact[interact.length-1].drag=(dx,dy)=>{b.position.x=THREE.MathUtils.clamp(b.position.x+dx*.009,-2.4,.6);b.position.y=THREE.MathUtils.clamp(b.position.y-dy*.009,-1.0,.9);const tx=-.6,ty=-.85+i*.18;const d=Math.hypot(b.position.x-tx,b.position.y-ty);if(d<.22){b.position.x=tx;b.position.y=ty;const q=Math.min(1,pRef.current+.18);setP(q,q>.82?'استقرت طبقات التاج وظهر الشكل المعماري.':'أكمل صف البناء.');sound('stone')}}}const crown=add(lathe([[.3,-.2],[.65,-.1],[.75,.1],[.55,.3],[.3,.25]],'#b5a88f',.82),'تاج العمود');crown.position.set(-.6,.15,.35);interact.push({object:crown,label:'التاج',drag:(dx,dy)=>{if(pRef.current<.72)return;crown.position.y=THREE.MathUtils.clamp(crown.position.y-dy*.009,-.05,.7);setP(Math.min(1,pRef.current+.03),pRef.current>.94?'اكتمل التاج.':'ارفع التاج فوق العمود.')}})}
 // 20 route
 else if(artifact.id===20){const ground=add(box(5,.16,3.2,'#705b45',.98),'طريق القوافل');ground.position.set(-.4,-1.22,.2);const route=new THREE.CatmullRomCurve3([new THREE.Vector3(-2,-.95,.5),new THREE.Vector3(-1.1,-.45,.5),new THREE.Vector3(-.2,-.75,.5),new THREE.Vector3(.8,-.2,.5),new THREE.Vector3(1.8,.05,.5)]);const road=new THREE.Mesh(new THREE.TubeGeometry(route,120,.08,12,false),mat('#c6a878',.95));root.add(road);const traveler=add(lathe([[.02,-.2],[.12,-.16],[.16,.05],[.1,.2],[.02,.25]],'#9fc4ae',.45,.05),'المسافر');traveler.position.copy(route.getPoint(0));for(let i=0;i<5;i++){const st=add(box(.38,.18,.38,'#8b7555',.9),'محطة');st.position.copy(route.getPoint(i/4));st.position.y+=.12}const well=add(cyl(.22,.3,'#6c6256',.9),'بئر');well.position.set(.6,-.8,.1);interact[interact.length-1].drag=(dx)=>{const q=THREE.MathUtils.clamp(pRef.current+dx*.0025,0,1);traveler.position.copy(route.getPoint(q));setP(q,q>.88?'وصل المسافر إلى المحطة الأخيرة.':'اسحب المسافر على الطريق بين المحطات.');sound('wood')}}
 dust=dust||particles(scene,80,'#c6b38c',7,3,.01)
 const resize=()=>{const w=Math.max(1,el.clientWidth),h=Math.max(1,el.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};const ro=new ResizeObserver(resize);ro.observe(el);resize();const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let active:Item|null=null,last={x:0,y:0}
 const hit=(e:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const hs=ray.intersectObjects(interact.map(x=>x.object),true);return hs[0]?.object||null};const find=(o:THREE.Object3D|null)=>{let c=o;while(c){const i=interact.find(x=>x.object===c);if(i)return i;c=c.parent}return null}
 const down=(e:PointerEvent)=>{renderer.domElement.setPointerCapture?.(e.pointerId);active=find(hit(e));last={x:e.clientX,y:e.clientY};if(active?.tap){active.tap();sound('click')}};const move=(e:PointerEvent)=>{if(!active)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;last={x:e.clientX,y:e.clientY};active.drag?.(dx,dy,new THREE.Vector3())};const up=(e:PointerEvent)=>{if(renderer.domElement.hasPointerCapture?.(e.pointerId))renderer.domElement.releasePointerCapture?.(e.pointerId);active=null}
 renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up)
 let raf=0;const start=performance.now();const loop=(now:number)=>{if(dead)return;raf=requestAnimationFrame(loop);const t=(now-start)/1000;camera.position.z=7.5;camera.position.y=.1;update(t);if(dust){dust.rotation.y+=.0003;dust.position.y=Math.sin(t*.25)*.025}renderer.render(scene,camera)};loop(start)
 return()=>{dead=true;cancelAnimationFrame(raf);ro.disconnect();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',up);renderer.dispose();if(renderer.domElement.parentNode===el)el.removeChild(renderer.domElement);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}})}
 },[artifact.id])
 return <div className="experienceWorldWrap"><div className="worldTitle"><span>3D SCENE · TOUCH FIRST</span><strong>{TITLES[artifact.id]||'تجربة القطعة'}</strong></div><div ref={host} className="experienceCanvas"/><div className="worldHint"><span className="hintPulse">👆</span><div><b>جرّب بنفسك</b><p>{HINTS[artifact.id]||'المس العناصر واسحبها. المشهد يستجيب مباشرة.'}</p></div></div><div className="worldStatus"><span>{message}</span><b>{Math.round(progress*100)}%</b><i><em style={{width:`${Math.round(progress*100)}%`}}/></i></div></div>
}
